spring.application.name=social-reel

cloudflare.r2.account-id=${ACCOUNT_ID}

cloudflare.r2.bucket=${BUCKET}

cloudflare.r2.access-key=${ACCESS_KEY}

cloudflare.r2.secret-key=${SECRET_KEY}

cloudflare.r2.public-base-url=${PUBLIC_BASE_URL}

spring.data.mongodb.posts.uri= ${MONGO_URI}

spring.jwt.secret=${JWT_SECRET}
