spring.application.name=social-reel

# MongoDB

spring.data.mongodb.uri=${MONGO_URI}

# JWT

spring.jwt.secret=${JWT_SECRET}

# Internal Service Authentication

service.secret=${SERVICE_SECRET}

# Cloudflare R2

cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.bucket=reels
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.public-base-url=${R2_PUBLIC_BASE_URL}

# Internal Service URLs

health.api=http://reel-service:8084/api/health
profile.uri=http://profile-service:8081
like.uri=http://likes-service:8083

# Server

server.port=8084

# Multipart Uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO

# Actuator / Metrics

management.endpoint.health.show-details=always
management.datadog.metrics.export.enabled=true
management.defaults.metrics.export.enabled=true

management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true

management.endpoint.web.base-path=/actuator
management.endpoints.web.exposure.include=*
